apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: switchbot-middleware
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: harbor.k8s.local/streamdeck_switchbot/switchbot-middleware
      context: app
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - manifests/deploy.yaml
    - manifests/ingress.yaml
    - manifests/vault-auth.yaml
    - manifests/vaultstaticsecret.yaml
    - manifests/configmap.yaml