apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: switchbot-middleware-vault-secret
spec:
  type: kv-v2
  mount: kv
  path: switchbot
  destination:
    name: switchbot-middleware-kv
    create: true
  refreshAfter: 30s
  vaultAuthRef: switchbot-middleware-vault-auth